### Get OAuth2 Access Token from Keycloak
POST http://lb-9e73af7a.elb.localhost.localstack.cloud:54479/realms/patient-management/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=postman-client&client_secret=mzNDzhHCdVYE91xvJJh4wM3vKXAuG8lR

> {%
    client.global.set("access_token", response.body.access_token);
%}

### Creates a new patient entity
POST http://lb-9e73af7a.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "John Doe Kafka Test",
  "email": "kafka_test2@example.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}


###