### Get OAuth2 Access Token from Keycloak
POST http://lb-e9f1edca.elb.localhost.localstack.cloud:8080/realms/patient-management/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=ms-api&client_secret=s3aOjP7nk9pmJapIgMAIuFJmzyhgqxOm

> {%
    client.global.set("access_token", response.body.access_token);
%}

### GET request to get all patients (with authentication)
GET http://lb-e9f1edca.elb.localhost.localstack.cloud:4004/api/patients
Authorization: Bearer {{access_token}}
